blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/WatheqAlshowaiter/model-required-fields/discussions/new?category=q-a
    about: Ask the community for help
  - name: Report a security issue
    url: https://github.com/WatheqAlshowaiter/model-required-fields/security/policy
    about: Learn how to notify us for sensitive bugs
